version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: ember-cli
    versions:
    - 3.25.1
    - 3.25.3
    - 3.26.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: ember-cli-babel
    versions:
    - 7.25.0
    - 7.26.1
    - 7.26.3
  - dependency-name: ember-source
    versions:
    - 3.25.3
    - 3.26.0
  - dependency-name: ember-cli-htmlbars
    versions:
    - 5.3.2
    - 5.6.0
    - 5.6.2
    - 5.6.3
    - 5.6.4
    - 5.6.5
    - 5.7.0
